--- 
- name: Get CDP info
  gather_facts: false
  hosts: all
  
  tasks: 
    - name: show cdp neighbors
      ios_command:
        commands: 
        - show cdp neighbors

      register: print_output

    - debug: var=print_output.stdout_lines
