---
  
- name: gather facts
  hosts: routers
  gather_facts: false

  tasks:
    - name: gather all legacy facts
      ios_facts:
        gather_subset: all

    - name: Display the config
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"
