---

- name: Get arp info
  hosts: all
  gather_facts: false

  tasks:
    - name: show arp
      ios_command:
        commands: show arp
      register: print_output

    - debug: var=print_output.stdout_lines
