---

- name: interface
  hosts: routers
  gather_facts: false
  
  tasks:
    - name: configure interface
      ios_interface:
        name: "{{ first_int }}"
        description: test-interface
        duplex: full

    - name: configure loopback
      ios_interface:
        name: "{{ loopback_int }}"
        state: present

    - name: make interface up
      ios_interface:
        name: "{{ first_int }}"
        enabled: true

    - name: make interface up
      ios_interface:
        name: "{{ loopback_int }}"
        enabled: true
