---

- name: interface
  hosts: routers
  gather_facts: false
  
  tasks:
    - name: configure interface
      ios_interface:
        name: FastEthernet1/0
        description: test-interface
        duplex: full

    - name: configure loopback
      ios_interface:
        name: Loopback9
        state: present

    - name: make interface up
      ios_interface:
        name: FastEthernet1/0
        enabled: true
