---

- name: Switchport module test
  hosts: switches
  gather_facts: false


  tasks:
    - name: InterVlan Routing with SVI
      ios_config:
        commands:
        - ip routing
        - interface vlan 10
        - ip address 192.168.1.254 255.255.255.0
        - no shutdown
        - interface vlan 20
        - ip address 192.168.2.254 255.255.255.0
        - no shutdown

