--- 
- 
  gather_facts: false
  hosts: routers
  name: interface
  tasks: 
    - 
      ios_l3_interfaces: 
        config: 
          - 
            ipv4: 
              - 
                address: "{{ first_int_ip }}"
            name: "{{ first_int }}"
          - 
            ipv4: 
              - 
                address: "{{ loopback_int_ip }}"
            name: "{{ loopback_int }}"
        state: merged
      name: "Merge provided configuration with device configuration"
