---

- name: show version
  hosts: routers
  gather_facts: false

  tasks:
    - name: show arp
      ios_command:
        commands: 
        - show version
        - show ip interface brief
      register: print_output

    - debug: var=print_output.stdout_lines
