---

ansible_ssh_user: cisco
ansible_ssh_pass: redhat
#ansible_connection: 'netcommon.network_cli'
ansible_connection: 'network_cli'
ansible_network_os: 'ios'
ansible_become: false
become: yes
ansible_python_interpreter: '/usr/bin/python3'
